In [1]:
#the tag/attribute of root node of the file
import xml.etree.ElementTree as ET
tree = ET.parse('blast_sample.xml')
root = tree.getroot()


print(root.tag)


BlastOutput


In [9]:
# matrix was used for alignment scoring
for each in root.findall('.//Parameters'):
         rating = each.find('.//Parameters_matrix')
         print(rating.text)


BLOSUM62


In [12]:
#number of similar sequences (Hits) as entry sequence in database
for each in root.findall('.//Hit'):
    similar_sequences = each.find('.//Hit_num')

print(similar_sequences.text)

49


In [13]:
#number of similar sequences (Hits) with less than 0.01 
for each in root.findall('.//Hsp'):
    value = each.find('.//Hsp_evalue')
    if value.text < '0.01':
       print(value.text)
    

0
0
0.000202995
0.000524953
0.00289628
0.00335949
0.00744792
0.00959789


In [14]:

#calculate the eigen values and eigen vectors of the matrix. 
import numpy as np
Matrix = np.matrix('2 4 6; 8 10 12; 14 16 18')
print(Matrix)

tMatrix = Matrix.transpose()
print(tMatrix)
from numpy import linalg as L
a, b = np.linalg.eig(Matrix)
print("Eigenvalues of Matrix is : ", a)
print("Eigenvector of Matrix is : ", b)
from numpy import linalg as L
c, d = np.linalg.eig(tMatrix)
print("Eigenvalues of Matrix is : ", c)
print("Eigenvector of Matrix is : ", d)
print("Eigenvector of Matrix is : ", d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
Eigenvalues of Matrix is :  [ 3.22336879e+01 -2.23368794e+00 -1.95183697e-15]
Eigenvector of Matrix is :  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
Eigenvalues of Matrix is :  [ 3.22336879e+01 -2.23368794e+00 -3.15346855e-16]
Eigenvector of Matrix is :  [[-0.46454727 -0.88290596  0.40824829]
 [-0.57079553 -0.23952042 -0.81649658]
 [-0.67704379  0.40386512  0.40824829]]
Eigenvector of Matrix is :  [[-0.46454727 -0.88290596  0.40824829]
 [-0.57079553 -0.23952042 -0.81649658]
 [-0.67704379  0.40386512  0.40824829]]


In [15]:
#calculate the singular value decomposition (SVD)
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
myU, mys, myV = np.linalg.svd(a, full_matrices=True)
myU.shape, myV.shape, mys.shape
((9, 9), (6, 6), (6,))
theS = np.zeros((9, 6), dtype=complex)
theS[:6, :6] = np.diag(mys)
print(np.diag(mys))


[[6.87790285 0.         0.         0.         0.         0.        ]
 [0.         4.58668357 0.         0.         0.         0.        ]
 [0.         0.         4.13612518 0.         0.         0.        ]
 [0.         0.         0.         3.31424993 0.         0.        ]
 [0.         0.         0.         0.         1.72742233 0.        ]
 [0.         0.         0.         0.         0.         0.82370929]]
